### ISSUE TITLE
The highlight plugin throws an exception if the current spineItem doesn't have a 'paginationInfo'

### ISSUE THREAD

**Issue by havarnov** [readium/readium-shared-js#315]
#### Expected Behaviour

The highlight manager should handle to add highlights event if the current context have a spineItem without paginationInfo.
#### Observed behaviour

The highlight plugin throws an TypeError if the current context have a spineItem without paginationInfo:

```
TypeError: Cannot read property 'isVerticalWritingMode' of undefined
    at Class._getPaginationLeftOffset (https://local.unibok.no:7011/js/thirdparty/readium/readium-plugin-highlights.js:1916:82)
    at Class.addHighlight (https://local.unibok.no:7011/js/thirdparty/readium/readium-plugin-highlights.js:1558:34)
    at HighlightsManager.options.addHighlight (https://local.unibok.no:7011/js/thirdparty/readium/readium-plugin-highlights.js:2104:53)
    at Object.addHighlight (https://local.unibok.no:7011/js/thirdparty/readium/readium-plugin-highlights.js:2367:39)
    at Object.colorHighlightAnnotation (https://local.unibok.no:7011/js/HighlightManager.js:101:55)
    at https://local.unibok.no:7011/js/views/ReaderView.js:971:61
    at Function._.each._.forEach (https://local.unibok.no:7011/js/thirdparty/readium/readium-external-libs.js:13642:9)
    at n.forEach (https://local.unibok.no:7011/js/thirdparty/backbone-1.3.3.min.js:1:774)
    at https://local.unibok.no:7011/js/views/ReaderView.js:968:65
```
#### Steps to reproduce
1. Start Readium with Readium::openPackageDocument where openPageRequest has idref and elementCfi.
### Product
- Web app which uses ReadiumJS to render epubs
  - tested on 0.23.0
  - any browser
  - any OS
#### Additional information

Readium::openPackageDocument indirectly calls ReaderView::openSpineItemElementCfi.
The spineItem is then found in ReaderView::openSpineItemElementCfi from the function getSpineItem and the returned spineItem doesn't have paginationInfo.

When the event 'Globals.Events.CONTENT_DOCUMENT_LOADED' is triggered the highlight plugin listens for this event and calls HighlightManager::attachAnnotations with the spineItem from before. Further down the call stack the private method HighlightController::_getPaginationLeftOffset is called and expects that the current spineItem has paginationInfo. Hence the plugin crashes with the TypeError mentioned earlier.

**Comment by danielweck** [comment]
Is that related to https://github.com/readium/readium-shared-js/issues/280 ?
